[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.poetry]
authors = []
description = "Basic load testing for Palace API"
name = "palace-api-load-test"
readme = "README.md"
version = "0"

[tool.poetry.dependencies]
locust = "^2.12.1"
python = ">=3.7,<4"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"
